# Site settings
author: Jamaal Smith
title: My Data Journey
header-img: img/home-bg.png
email: jdsmith1906@gmail.com
copyright_name: Jamaal Smith
description: > # this means to ignore newlines until "baseurl:"
  A real-time journal of my adventure tackling data science
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jdsmithwes

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
